version: '3'

services:

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./www/:/var/www/
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - "9999:9999"
    links:
      - "api01"
      - "api02"
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"


  api01: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api01
    container_name: api01
    user: "1000:1000"
    volumes:
      - ./www/:/var/www/
    links:
      - "db"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "2400MB"

  api02:
    <<: *api 
    hostname: api02
    container_name: api02
  

  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: api_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres/script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./postgres/pgsql.conf:/etc/postgresql/postgresql.conf
    command: 'postgres -c config_file=/etc/postgresql/postgresql.conf'  
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "100MB"


networks:
    default:
      driver: bridge
      name: rinha